### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by TheFixDev** [FlxiBoy1313/Perks#1]
Hallo, ich hätte eine Frage könnte man für das PerkSystem das so machen das das Speed Perk jetzt als Beispiel 50000$ Kostet ingame also pro Perk immer Geld ausgeben muss

**Comment by FlxiBoy1313** [comment]
Gerne, ich habe es auf die ToDo liste geschrieben und werde es demnächst adden. :)

**Comment by TheFixDev** [comment]
Okay cool 😄👍

**Comment by FlxiBoy1313** [comment]
Ich sollte fertig sein, nimm die Neuste Version von Poggit (https://poggit.pmmp.io/ci/FlxiBoy1313/Perks/Perks/3), ich habe in die Version das Geld geaddet, die Nachrichten geaddet, paar bugs behoben z.B das mit den Permissions und zudem eine bessere und übersichtlichere Config. Bei weiteren Fragen oder auch Bugs kannst du dich gerne hier melden :).
Viel Spaß mit meinem PerkSystem,
FlxiBoy.
