### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by chisi21** [FlxiBoy1313/Perks#11]
please add 

**configuration**

•Expired Time
true/false configuration expired time (if you buy one perk, there is a validity period of several days, hours or minutes. If the validity period expires, the perk cannot be used and must buy again) 
Example:
Keep Inventory:
       Perm: keep.inven
       Price: 10000
       Img: "textures"
       Expired time: true/false (**true** with expired time, **false** unlimited time) 
       Time: 60 minutes (for days, hours, minutes, seconds using the minutes format) 

**New Perk** 
•Keep XP

**Comment by FlxiBoy1313** [comment]
Thanks for your Idea.
This idea is really good and I just wrote it down for just. Keep-XP is already planned and the next updates will come as well as your idea now.
FlxiBoy.

**Comment by chisi21** [comment]
> Thanks for your Idea.
> This idea is really good and I just wrote it down for just. Keep-XP is already planned and the next updates will come as well as your idea now.
> FlxiBoy.

I will wait for it :D
