### ISSUE TITLE
Time 

### ISSUE THREAD

**Issue by djmaisen** [FlxiBoy1313/Perks#17]
Wenn ich die config ändere und das economy-api auf true setzte müsste ich doch die dauert der Effekte ändern können? 
Habe es jetzt auf "0:0:0:0:15:0" gesetzt und ingame wird immer noch über 9000 Minuten  angezeigt.

**Comment by FlxiBoy1313** [comment]
Okay thanks, I'll check it out.

**Comment by djmaisen** [comment]
Hab erst jetzt gesehen das du deutsch kannst xD

**Comment by FlxiBoy1313** [comment]
okay, alles gut xd

**Comment by djmaisen** [comment]
Sorry, Minuten, nicht Stunden

**Comment by FlxiBoy1313** [comment]
Kurze neben frage, könntest du vllt. die genauen konfigurationen schicken und schicken was du genau gemacht hast vom ändern bis zum öffnen des UIs?

**Comment by FlxiBoy1313** [comment]
Also ich habe es mir angeguckt, jedoch ist mir dort nichts aufgefallen. Ich habe jetzt nochmal was geändert wo ich Bugs gefunden habe, das heißt du kannst die neuste Version installieren und erneut probieren. Sollte dies nicht gehen kannst du /perks reload machen dann werden die Configs neugeladen und dann sollte es übernommen werden. Im nächsten Update kommen GUIs deswegen dauert das Update gerade solange jedoch werde ich dazu noch was machen und Verbesserungen das es einfacher wird und auch einfacher wird.
FlxiBoy.

**Comment by djmaisen** [comment]
######################
######################
####                               ####
####     Perks System     ####
####                               ####
######################
######################

# language list: english, german, russian
# more languages? please open a issues on github for a new language.
language: german

# command, edit the perks command
command:
  cmd: "perks"
  desc: "Open the Perks UI"
  usage: "§cUsage: /perks"
  aliases: "perks"
  reload:
    usage: "§cUsage: /perks <reload>"
    perms: perks.reload
  # if false, then this does not apply. if you write something, then the command goes.
  permission: false

settings:
  # If this is true, you can only buy with the price. If this is false, it goes to Permissions.
  economy-api: true
  friends:
    # if this and 'economy-api' true, then you can give friends perks.
    enable: false
    menu-img: "textures/ui/Friend2"
    yes-img: "textures/ui/confirm"
    no-img: "textures/ui/redX1"
    # if this true, then a UI will be opened to the person who has bought a perk
    open-ui: true
  perk-time:
    # if this and 'economy-api' true, then perks will only be there for a certain time.
    enable: true
    # %year% => is the year
    # %month% => is the month
    # %day% => is the day
    # %hour% => is the hour
    # %minute% => is the minute
    format: "§e%year% §ayear, §e%month% §amonth, §e%day% §aday, §e%hour% §ahour, §e%minute% §aminute"
  buy-confirm:
    # if this true, then a query is made before buying
    enable: true
    yes-img: "textures/ui/confirm"
    no-img: "textures/ui/redX1"
  double-jump:
    # This sets the strength of the double jump.
    strength: 2
    # if this is true, then the player does not take any fall damage
    falldamage: true
  auto-smelting:
    # if this is true then the items will be melted.
    enable: true
    # this is what makes the price of smelting
    price: 150
  perks-strength:
    # this is the max strength of perk strength
    strength: 5

# category
#   tutorial
#      category:
#        <number +>:
#           name: "<category-name>:<picture false is disable>"
#           perks: 
#             - "<perk-names>"
#  perk-list: "speed", "jump", "haste", "night-vision", "no-hunger", "no-falldamage", "fast-regeneration", "keep-inventory", "dopple-xp", "strength", "no-firedamage", "fly", "water-breathing", "invisibility", "keep-xp", "double-jump", "auto-smelting"
category:
  0:
    name: "§5Effects:textures/ui/absorption_effect"
    perks:
      - "speed"
      - "jump"
      - "haste"
      - "night-vision"
      - "fast-regeneration"
      - "strength"
      - "no-firedamage"
      - "water-breathing"
      - "invisibility"
  1:
    name: "§2Others:textures/ui/more-dots"
    perks:
      - "no-hunger"
      - "no-falldamage"
      - "keep-inventory"
      - "dopple-xp"
      - "fly"
      - "keep-xp"
      - "double-jump"
      - "auto-smelting"

# perks
perk:
  # perms => if you set it to false, anyone can use it. With a permission, this is only possible if a player has did permission.
  # price => will only go if you have 'economy-api' to true. This sets the price of the perks.
  # img => there you can add your picture or a picture of minecraft. false is disable the img. Is your picture not loading? Then install FormImagesFix.
  # time => if 'economy-api' true, this tells how long you can use a perk after buying it and then buy it again.
  #               0:0:0:0:0:0 => Year:Month:Day:Hour:Minute:Second => 0:0:6:24:59:59 (time zone => your server location)
  perms:
    # if this true, then only the perks are shown, as you also have hats or the permission, the perks should go with permission.
    enable: false
  speed:
    perms: perks.speed
    price: 10000
    img: "textures/ui/speed_effect"
    time: "0:0:0:0:15:0"
  jump:
    perms: perks.jump
    price: 10000
    img: "textures/ui/jump_boost_effect"
    time: "0:0:0:0:15:0"
  haste:
    perms: perks.haste
    price: 10000
    img: "textures/ui/haste_effect"
    time: "0:0:0:0:15:0"
  night-vision:
    perms: perks.night-vision
    price: 10000
    img: "textures/items/potion_bottle_nightVision"
    time: "0:0:0:0:30:0"
  no-hunger:
    perms: perks.no-hunger
    price: 10000
    img: "textures/ui/hunger_full"
    time: "0:0:0:0:20:0"
  no-falldamage:
    perms: perks.no-falldamage
    price: 10000
    img: "textures/items/totem"
    time: "0:0:0:0:30:0"
  fast-regeneration:
    perms: perks.fast-regeneration
    price: 10000
    img: "textures/ui/regeneration_effect"
    time: "0:0:0:0:10:0"
  keep-inventory:
    perms: perks.keep-inventory
    price: 10000
    img: "textures/ui/inventory_icon"
    time: "0:0:0:0:30:0"
  dopple-xp:
    perms: perks.dopple-xp
    price: 10000
    img: "textures/ui/dust_selectable_2"
    time: "0:0:0:0:10:0"
  strength:
    perms: perks.stren
    price: 10000
    img: "textures/ui/strength_effect"
    time: "0:0:0:0:15:0"
  no-firedamage:
    perms: perks.no-firedamage
    price: 10000
    img: "textures/ui/fire_resistance_effect"
    time: "0:0:0:0:10:0"
  fly:
    perms: perks.fly
    price: 10000
    img: "textures/items/feather"
    time: "0:0:0:0:15:0"
  water-breathing:
    perms: perks.water-breathing
    price: 10000
    img: "textures/ui/water_breathing_effect"
    time: "0:0:0:0:15:0"
  invisibility:
    perms: perks.invisibility
    price: 10000
    img: "textures/ui/invisibility_effect"
    time: "0:0:0:0:5:0"
  keep-xp:
    perms: perks.keep-xp
    price: 10000
    img: "textures/ui/dust_selectable_1"
    time: "0:0:0:1:0:0"
  double-jump:
    perms: perks.double-xp
    price: 10000
    img: "textures/items/iron_boots"
    time: "0:0:0:0:15:0"
  auto-smelting:
    perms: perks.auto-smelting
    price: 10000
    img: "textures/blocks/furnace_front_on"
    time: "0:0:0:0:10:0"

**Comment by FlxiBoy1313** [comment]
Ist dies immernoch bei dir?

**Comment by djmaisen** [comment]
Ja, immer noch. 
![Screenshot_20210812-114952_Minecraft](https://user-images.githubusercontent.com/66331684/129177298-57531fe4-4d14-48df-8da8-2a7648be1e63.jpg)

**Comment by FlxiBoy1313** [comment]
Dies ist dich Korrekt? Die Stunden werden nur 1 Stunde minus gemacht da die Zeitzone 1 stunde zurück ist.

**Comment by djmaisen** [comment]
Verstehe ich nicht???
Ich dachte 0:0:0:0:15:0 heißt 
Jahre:Monate:Tage:Stunden:Minuten:Sekunden
Also wie bei meiner config, dass der Effekt 15 Minuten anhält.
Oder wie muss ich das ändern damit der Effekt nur 15 min wirksam ist.

**Comment by FlxiBoy1313** [comment]
Achso so meinst du es, die Zahl die gesendet wird bzw die Zahlen, das bedeutet, bis wann er das Perk hat. Das heißt wenn du 15 Minuten hast, werden bei Minuten 15 drauf gepackt da er sie bis dahin nutzen kann. Hast du es verstanden? Oder eine genauere Beschreibung?

**Comment by djmaisen** [comment]
Kann man das nicht irgendwie einstellen, dass der Spieler nur 15 min das Perk nutzen kann? Wenn er das so lange verwenden kann ist es für meinen Server nutzlos. Dafür gibt es bei uns Ränge die individuelle Fähigkeiten besitzen die man für ingame Geld kaufen kann. Wenn er sich aber mit dem Anfang Rang schon z.B. fly kaufen kann das so lange hält wird er sich keinen höheren Rang mehr beschaffen.

**Comment by FlxiBoy1313** [comment]
Also, die Perks, die wo mit Zeit sind, z.B 15 min sind, die laufen auch nur 15 Min okay? Im Chat wird angezeigt ab wann du dieses Perk nicht mehr hast. Also wenn du ein Perk für 15 Min hast, dann wird dort angezeigt deine Aktuelle Zeit + diese 15 Min also 2021.08.15 20:20, verstehst du?

**Comment by djmaisen** [comment]
Aber warum wird dann so eine große Anzahl an Minuten angegeben? 
![Uploading Screenshot_20210815-202657_Minecraft.jpg…]()

**Comment by FlxiBoy1313** [comment]
Schicke bitte ein Bild, wo ich auch gucken kann, kann dies aktuell nicht angucken.

**Comment by FlxiBoy1313** [comment]
Ja, das kommt immer so. Nach 15 wird dies auf 0 gesetzt. bzw solange, du auch das Perk hast.

**Comment by djmaisen** [comment]
Also heißt das, man soll die angegebene Zeit ignorieren. Ist das dann so, dass sich der Spieler das Perk wieder von neuen kaufen kann?

**Comment by FlxiBoy1313** [comment]
Ja, habe. Nach der Zeit wird der Effect gelöscht und dann später neugegeben. Jedoch sehe ich gerade, das der Effect nicht entfernt wird. Ich werde es kurz rein machen und werde dir schreiben, wenn du es downloaden kannst.

**Comment by djmaisen** [comment]
Okay, danke für die Zeit die du dir nimmst. 👍🏼

**Comment by FlxiBoy1313** [comment]
So, in der neuen Version habe ich nun rein gemacht das die Effecte entfernt werden sowie beim Join auch gecheckt wird ob die Zeit um ist.

**Comment by FlxiBoy1313** [comment]
Sollte noch etwas sein, Reopen oder neues öffnen.
