### ISSUE TITLE
 die timer / zeit angabe funkzoniert nicht 

### ISSUE THREAD

**Issue by Unaskedcorn** [FlxiBoy1313/Perks#18]
ich habe auf mein server die timer auf True gesetzt und habe alles eingestellt aber tut sich nichts was timmer / wan das perk ablaufen soll. das klappt einfach nicht. oder verstehe ich was falsch am system 0:0:7:0:0:0 sind das jetzt 7 tage oder ? ich hab echt fast alles rum prubiert aber es klappt nicht.

**Comment by FlxiBoy1313** [comment]
Die Zeit Angabe funktioniert schon, jedoch wird es nur geprüft wenn man in die jeweilige Kategorie geht. Kann aber heute rein machen, das jede Minute gecheckt wird ob  die Perk zeit vorbei ist.

**Comment by Unaskedcorn** [comment]
ja danke das wäre echt eine gute erleichterung . wenn ich es sagen darf das zeit/timer Funktion ist ein wenig kompliziert . ich denke das es möglich ist das system leichter zu machen ich habe zwar keine keine Ahnung vom php oder java aber ich denke es ist möcglich.

**Comment by FlxiBoy1313** [comment]
Jup ist einfach. Jedoch kann ich dies nicht direkt machen da ich jetzt wo hinfahre. Werds aber danach direkt machen.

**Comment by FlxiBoy1313** [comment]
So, in der neusten Version ist nun drinnen. :)

**Comment by Unaskedcorn** [comment]
danke
