### ISSUE TITLE
Vorschlag für ein plugin

### ISSUE THREAD

**Issue by GamerMJay2008** [FlxiBoy1313/Perks#20]
Hey, ich hab ein Vorschlag für ein plugin wie wäre es den mit einem RangShop? wo man vllt auch anderen spielern über einen button auch einen rang schenken/kaufen kann

**Comment by FlxiBoy1313** [comment]
Eigt. eine Gute Idee. Jedoch habe ich jetzt in der Zeit nicht mehr viel Zeit. Ich habe auch letztens angefangen nen eigenen Server zumachen was groß wird, zudem bin ich in einem Server Team wo ich ein AntiCheat Code, sowie bei einem anderen Server TNTRun und BedWars, dann noch alle sachen für Public, also wird es sich alles jetzt verzögern. Jedoch kannst du diese Idee [supercrafter333](https://github.com/supercrafter333) stellen, er programmiert auch PocketMine Plugins und hat soweit ich weiß, auch aktuell mehr Zeit.

**Comment by GamerMJay2008** [comment]
Okay das werde ich mal machen
