### ISSUE TITLE
Vorschlag

### ISSUE THREAD

**Issue by GamerMJay2008** [FlxiBoy1313/Perks#22]
Guten Abend/Tag Ich hätte ein Vorschlag für das Plugin 😅 Nämlich das man Perks in bestimmten welten deaktivieren kann

- Mit freundlichen Grüßen GamerMJay2008 😀

**Comment by FlxiBoy1313** [comment]
Okay, gut Idee. Ich werde es demnächst umsetzen 👍🏻

**Comment by GamerMJay2008** [comment]
Ah Okay danke dir und danke für die Schnelle Antwort 👍
