### ISSUE TITLE
Bubbel ist Bubbelig

### ISSUE THREAD

**Issue by MonoAdrian23** [FlxiBoy1313/Perks#23]
Bubbel bubbelt Bubbel Bubbelig!
Bubbelige Bubbelgrüße!

**Comment by FlxiBoy1313** [comment]
xd cute :happy:

**Comment by MonoAdrian23** [comment]
Hab ich gern da gelassen.
Mach weiter so mein Guter

**Comment by FlxiBoy1313** [comment]
danke dir <3

**Comment by FlxiBoy1313** [comment]
wird gemacht Chef.

**Comment by GamerMJay2008** [comment]
HOHEIT
