### ISSUE TITLE
API4 support?!

### ISSUE THREAD

**Issue by GamerMJay2008** [FlxiBoy1313/Perks#27]
Hey, wird das Perks plugin auf die API 4 geupdatet?

**Comment by FlxiBoy1313** [comment]
Ja, ich sitze bereits dran. Ich denke laufend des Wochenende wird die Version für PM4 erscheinen.

**Comment by GamerMJay2008** [comment]
Okay nice

**Comment by FlxiBoy1313** [comment]
API4 wird nun Supportet. Auf Poggit kannst du gerne die neue Datei herunterladen. Jedoch kann es noch zu Fehlern kommen. Ich sitze dran alles zu suchen und auch zu fixen.

**Comment by GamerMJay2008** [comment]
Ah okay ich danke dir vom Herzen 😅😄
