### ISSUE TITLE
Fehler/bug?!

### ISSUE THREAD

**Issue by GamerMJay2008** [FlxiBoy1313/Perks#28]
![Screenshot_2021-11-23-20-08-21-49](https://user-images.githubusercontent.com/66413999/143088267-3153875f-7f84-4036-99f9-2514e0f89b60.jpg)

Hey ich wollte mal fragen is das normal?
API3

**Comment by GamerMJay2008** [comment]
J

**Comment by GamerMJay2008** [comment]
Ja*

**Comment by FlxiBoy1313** [comment]
Ist das bereits die ganze Zeit an und ist es erst seit dem Update?

**Comment by GamerMJay2008** [comment]
Weiß ich gerad garnd

**Comment by GamerMJay2008** [comment]
Also ich hab alles resetet config, players, language

**Comment by GamerMJay2008** [comment]
und es geht immernoch nicht

**Comment by FlxiBoy1313** [comment]
Sind deine Perks auch gekauft? Weil wenn man sie kaufen muss, und dort die gekauften Perks angezeigt werden.

**Comment by GamerMJay2008** [comment]
Hab eingestellt das man sie nicht kaufen kann sondern das man die Perms braucht für jedes Perk

**Comment by FlxiBoy1313** [comment]
hast du API4?

**Comment by GamerMJay2008** [comment]
Ne benutze API3

**Comment by FlxiBoy1313** [comment]
hm

**Comment by FlxiBoy1313** [comment]
Da kann ich dir wirklich nicht helfen. Tut mir leid.

**Comment by FlxiBoy1313** [comment]
Ich mache jetzt sowieso eine neue weitere Version, ich werde es mir nochmals genau angucken und vllt liegt wirklich ein Fehler vor.

**Comment by FlxiBoy1313** [comment]
Versuche es jetzt mit dieser Version @GamerMJay2008
