### ISSUE TITLE
/perks crashed the Server

### ISSUE THREAD

**Issue by PocketMiner92** [FlxiBoy1313/Perks#31]
[Sun_Dec_19-08.13.47-CET_2021.log](https://github.com/FlxiBoy1313/Perks/files/7740446/Sun_Dec_19-08.13.47-CET_2021.log)

**Comment by FlxiBoy1313** [comment]
Thanks. I will fix this.

**Comment by FlxiBoy1313** [comment]
Hello, could you maybe give me more info about it? In this case there is nothing I can do about it. If you help me we can surely find a solution.

**Comment by FlxiBoy1313** [comment]
Please use the new version from poggit, Dev 72. This is fixed.
