### ISSUE TITLE
ECONOMYAPI Glitch

### ISSUE THREAD

**Issue by thunderfurry** [FlxiBoy1313/Perks#33]
When turning on EconomyAPI, then the server crashes when you try to open perks and turn on a perk, please fix this.
![image](https://user-images.githubusercontent.com/91995526/148606660-517799a1-e03c-4696-8deb-d8f9afc1557a.png)

**Comment by FlxiBoy1313** [comment]
pls send the error.

**Comment by thunderfurry** [comment]
Sorry
I literally just updated, to show.

Here it is again
![image](https://user-images.githubusercontent.com/91995526/148606740-9ace52fb-d6d0-4bb3-b47f-638c4434af38.png)

**Comment by thunderfurry** [comment]
I think it doesn't know what to replace the message with, but **I don't even know PHP**

**Comment by FlxiBoy1313** [comment]
Could you tell me which form the error comes from?

**Comment by thunderfurry** [comment]
Effects, Others, and the friend one, also pressing X but that is caused by the friends thing ¯\_(ツ)_/¯

**Comment by FlxiBoy1313** [comment]
Okay thanks, I'll check it out

**Comment by thunderfurry** [comment]
I can show you a video:
https://cdn.discordapp.com/attachments/839877330871910400/929119068810788894/Minecraft_2022-01-07_13-06-16.mp4

**Comment by thunderfurry** [comment]
Also, please tell me once you fix it, also it shows the file
src/flxiboy/api/API

**Comment by thunderfurry** [comment]
![image](https://user-images.githubusercontent.com/91995526/148608449-cde99ac5-0e45-4f75-8124-6e26fb274ff5.png)
The current image doesn't really look good also, so i made one 4 u
![Perkz](https://user-images.githubusercontent.com/91995526/148608529-6478dc2a-6fd9-4c38-a2a9-170901d0a3ed.png)

**Comment by FlxiBoy1313** [comment]
Here is the fix: https://poggit.pmmp.io/ci/FlxiBoy1313/Perks/Perks/81

**Comment by thunderfurry** [comment]
Thank you! I can't wait to re-re-re-install it because i never look at Crash.Pmmp.Io

**Comment by FlxiBoy1313** [comment]
okay 👌

**Comment by FlxiBoy1313** [comment]
can I help you with anything else, or is that all?

**Comment by thunderfurry** [comment]
I need help with knowing how to buy perks :I

**Comment by FlxiBoy1313** [comment]
so how do you change prices?

**Comment by thunderfurry** [comment]
No, How do i get the perks when I have the money.

**Comment by FlxiBoy1313** [comment]
By clicking on the perks, if you have settings.buy-confirm.enable set to true in the config, you will get a UI where you can buy it.

**Comment by thunderfurry** [comment]
oh
OKAY
O H
O    H
OH

**Comment by thunderfurry** [comment]
Thanks for fixing the plugin, because other people would want to have it, and then their server would crash, NOT ANYMORE! good job!

**Comment by thunderfurry** [comment]
Now for a good close with comment, Great Plugin!

**Comment by FlxiBoy1313** [comment]
thanks ❤️
