### ISSUE TITLE
IDEA  SERVER FULL

### ISSUE THREAD

**Issue by CRISTININIMIS** [FlxiBoy1313/Perks#35]
It is an advantage that when a server is full the server lets in the person who has a rank or the one you decide

**Comment by FlxiBoy1313** [comment]
Okay, I'll see what I can do.

**Comment by FlxiBoy1313** [comment]
The message comes from Minecraft.
![image](https://user-images.githubusercontent.com/65186341/156370629-2cd7c0c0-3187-434c-a06a-0704e82f3aaf.png)

**Comment by PocketMiner92** [comment]
You can Change the Range of Player in server.properties
A Plugin is useless
