### ISSUE TITLE
EconomyAPI Crash

### ISSUE THREAD

**Issue by Tuvqlu** [FlxiBoy1313/Perks#36]
Hi when you enable it for eco api it’s crashes pls fix thanks : D

**Comment by FlxiBoy1313** [comment]
Pls send the error

**Comment by PocketMiner92** [comment]
Bubbel needs an Error!!!!

**Comment by PocketMiner92** [comment]
Bubbel Errors are Epic Today.
You must send youre Crashdump or a Log!

**Comment by Tuvqlu** [comment]
Works now! Thanks! This will help my server a LOT
